CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE league (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id BIGINT UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id BIGINT UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE league_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    league_id BIGINT NOT NULL,
    CONSTRAINT uk_league_preference_user_league UNIQUE (user_id, league_id),
    CONSTRAINT fk_league_preference_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_league_preference_league
        FOREIGN KEY (league_id) REFERENCES league (id)
);

CREATE TABLE soccer_match (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id BIGINT UNIQUE,
    league_id BIGINT NOT NULL,
    home_team_id BIGINT NOT NULL,
    away_team_id BIGINT NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    home_score INTEGER,
    away_score INTEGER,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT fk_soccer_match_league
        FOREIGN KEY (league_id) REFERENCES league (id),
    CONSTRAINT fk_soccer_match_home_team
        FOREIGN KEY (home_team_id) REFERENCES team (id),
    CONSTRAINT fk_soccer_match_away_team
        FOREIGN KEY (away_team_id) REFERENCES team (id),
    CONSTRAINT ck_match_different_teams CHECK (home_team_id <> away_team_id)
);
